language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.11
  - 2.12.4

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers/

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile tests/test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

after_success:
  - bash <(curl -s https://codecov.io/bash)
