language: scala

jdk:
  - openjdk8

scala:
  - 2.11.12
  - 2.12.9
  - 2.13.0

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers/

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

after_success:
  - bash <(curl -s https://codecov.io/bash)
